### ISSUE TITLE
PostgreSQL JSON result handled improperly?

### ISSUE THREAD

**Issue by bladeoflight16** [jakefeasel/sqlfiddle#77]
See this fiddle: http://sqlfiddle.com/#!15/5860d/11
It gives this result:
``` 
{ "Value": "[{\"a\":1,\"b\":\"value1\"},{\"a\":2,\"b\":\"value2\"},{\"a\":3,\"b\":\"value3\"}]", "Type": "json" }
```
When I run the same set of commands directly against PostgreSQL, I get the following result:
```
[{"a":1,"b":"value1"},{"a":2,"b":"value2"},{"a":3,"b":"value3"}]
```

It seems that SQLFiddle is adding some kind of wrapping around the JSON string in the result. It escapes the string from the result, maps the escaped result to a `"Value"` key in a JSON object, and adds a `"Type": "json"` key/value.

Affects PostgreSQL 9.2 and up (since the JSON features were introduced).

**Comment by bladeoflight16** [comment]
This appears to be fixed now. I dunno how or when.

**Comment by jakefeasel** [comment]
Was fixed in the new codebase jakefeasel/sqlfiddle2#18
